version: '3.3'

services:
  web:
    container_name: php_7
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./www:/var/www/html/
      - ./docker-compose/apache:/etc/apache2/sites-available
    ports:
      - 8000:80
    depends_on:
      - database
    networks:
      - apachephp

  database:
    container_name: mysql_latest
    image: mysql:latest
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    networks:
      - apachephp

networks:
  apachephp:
    driver: bridge